# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.label_input.setFont(font)
        self.label_input.setStyleSheet("background-color: rgb(184, 133, 255);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_input.setObjectName("label_input")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(100, 50, 100, 50))
        self.btn_0.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_0.setObjectName("btn_0")
        self.btn_is_equal_to = QtWidgets.QPushButton(self.centralwidget)
        self.btn_is_equal_to.setGeometry(QtCore.QRect(0, 300, 200, 100))
        self.btn_is_equal_to.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_is_equal_to.setObjectName("btn_is_equal_to")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 250, 100, 50))
        self.btn_1.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 250, 100, 50))
        self.btn_2.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_2.setObjectName("btn_2")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(100, 200, 100, 50))
        self.btn_4.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_4.setObjectName("btn_4")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(0, 200, 100, 50))
        self.btn_3.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_3.setObjectName("btn_3")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(0, 150, 100, 50))
        self.btn_5.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(100, 150, 100, 50))
        self.btn_6.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 100, 100, 50))
        self.btn_7.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 100, 100, 50))
        self.btn_8.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(0, 50, 100, 50))
        self.btn_9.setStyleSheet("background-color: rgb(208, 206, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_9.setObjectName("btn_9")
        self.btn_clean_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean_up.setGeometry(QtCore.QRect(200, 330, 100, 70))
        self.btn_clean_up.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_clean_up.setObjectName("btn_clean_up")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(200, 260, 100, 70))
        self.btn_plus.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(200, 190, 100, 70))
        self.btn_minus.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiplication.setGeometry(QtCore.QRect(200, 120, 100, 70))
        self.btn_multiplication.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_multiplication.setObjectName("btn_multiplication")
        self.btn_division = QtWidgets.QPushButton(self.centralwidget)
        self.btn_division.setGeometry(QtCore.QRect(200, 50, 100, 70))
        self.btn_division.setStyleSheet("background-color: rgb(218, 186, 255);\n"
"font: 87 15pt \"Arial Black\";\n"
"color: rgb(82, 0, 223);")
        self.btn_division.setObjectName("btn_division")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label_input.setText(_translate("MainWindow", "0"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_is_equal_to.setText(_translate("MainWindow", "="))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_clean_up.setText(_translate("MainWindow", "clean up"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_multiplication.setText(_translate("MainWindow", "*"))
        self.btn_division.setText(_translate("MainWindow", "/"))


    def add_function(self):
        self.btn_0.clicked.connect(lambda: self.write_number(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_multiplication.clicked.connect(lambda: self.write_number(self.btn_multiplication.text()))
        self.btn_division.clicked.connect(lambda: self.write_number(self.btn_division.text()))
        self.btn_clean_up.clicked.connect(self.clean_up)

        self.btn_is_equal_to.clicked.connect(self.results)

    def write_number(self, number):
        if self.label_input.text() == '0':
            self.label_input.setText(number)
        else:
            self.label_input.setText(self.label_input.text() + number)

    def clean_up(self):
        self.label_input.setText("0")

    def results(self):
        res = eval(self.label_input.text())
        self.label_input.setText(str(res))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
